name: cripto_chat
description: Projeto PEPE Chat multiplataforma com Supabase Auth
version: 1.0.0

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  supabase: ^2.4.2
  supabase_flutter: ^2.3.3
  google_fonts: ^6.2.0
  image_picker: ^1.0.7
  file_picker: any
  url_launcher: ^6.2.5
  any_link_preview: ^3.0.1
  intl: ^0.19.0
  youtube_player_flutter: ^9.1.1
  audioplayers: ^5.0.1
  app_links: ^3.4.1
  flutter_cube: ^0.1.1
  rive: ^0.12.4
  shared_preferences: ^2.2.3
  vector_math: ^2.1.4
  flame: ^1.12.0
  model_viewer_plus: ^1.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon_bolhas.png"